apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
spec:
  replicas: 3
  selector:
    matchLabels:
      role: back-end
  template:
    metadata:
      labels:
        role: back-end
    spec:
      containers:
      - name: back-end
        image: angeldiaz3005/cc-parcial:back-end2
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: back-end-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    role: back-end
